theme: jekyll-theme-minimal
title: Amplicon Data Analysis
description: Basic theory and complete workflow for 16S rRNA gene sequencing analysis from raw reads to statistics and plots.
show_downloads: false
